name: Firebase CI

on:
  push: branches:main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js version ${{ matrix.node-version }}
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-verstion }}
      - name: Install Dependencies
        run: npm install
      - run: npm install -g firebase-tools
      - run: npm run test
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
